//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_zed_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.zed_default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.zed_default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 NavigateUI
        {
            get
            {
                return SteamVR_Actions.zed_default_NavigateUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Click
        {
            get
            {
                return SteamVR_Actions.zed_default_Click;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.zed_default_Back;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.zed_default_Fire;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.zed_default_Haptic;
            }
        }
    }
}
